# Exemplo de configuração para rodar a análise por NOME (sem IDs)
data_root: /caminho/para/seu/clone/open-data   # deve conter a pasta data/
out: ./saida_pl_2015_16
scope:
  competition: Premier League    # nome conforme competitions.json
  season: 2015/2016              # exatamente como está no arquivo
  # team: Arsenal                # opcional: para filtrar só os jogos do time
prob_threshold: 0.05             # arestas mínimas para o grafo
