open_data_repo_dir: ./_open_data_repo/data

paths:
  interim: data/interim
  outputs: data/outputs

filters:
  competitions: [2]
  seasons: [27]
  matches: []
  teams: []

field:
  x_max: 120
  y_max: 80
  thirds_x: [40, 80]
  lanes_y: [26.6667, 53.3333]

actions:
  include: ["pass", "carry", "dribble", "shot", "clearance"]
  map_other_to: "other"
  include_ball_receipt_in_edges: false
  carry_zone_from_end_location: true

alpha_smoothing: 0.3
treat_shot_as_terminal: true
random_seed: 42