# Caminho para a pasta de dados. Opcional, o padrão é ./_open_data_repo
# data_root: "~/open-data"

# Onde salvar os arquivos de saída (CSVs, grafo)
out: ./saida_config

# Escopo da análise: nomes da competição e temporada
scope:
  competition: "Premier League"
  season: "2015/2016"
  # team: "Leicester"  # Opcional: filtre por um time específico

# Limiar de probabilidade para desenhar uma aresta no grafo
prob_threshold: 0.05
